/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'client-accounts': ClientAccount;
    'client-transaction': ClientTransaction;
    'vendor-transaction': VendorTransaction;
    expense: Expense;
    vendor: Vendor;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'client-accounts': ClientAccountsSelect<false> | ClientAccountsSelect<true>;
    'client-transaction': ClientTransactionSelect<false> | ClientTransactionSelect<true>;
    'vendor-transaction': VendorTransactionSelect<false> | VendorTransactionSelect<true>;
    expense: ExpenseSelect<false> | ExpenseSelect<true>;
    vendor: VendorSelect<false> | VendorSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'manager' | 'guest';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-accounts".
 */
export interface ClientAccount {
  id: number;
  clientName: string;
  clientMobile: string;
  query_license: string;
  mining_license?: string | null;
  near_village: string;
  tehsil?: string | null;
  district?: string | null;
  state?: string | null;
  country?: string | null;
  clientCreatedAt?: string | null;
  clientUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-transaction".
 */
export interface ClientTransaction {
  id: number;
  clientName: number | ClientAccount;
  query_license: number | ClientAccount;
  near_village: number | ClientAccount;
  workingStage?:
    | {
        workingStage?: string | null;
        workingDescription?: string | null;
        workstatus?: string | null;
        id?: string | null;
      }[]
    | null;
  workingStageclient?:
    | {
        workingStageclient?: string | null;
        workingDescriptionclient?: string | null;
        stageDate: string;
        id?: string | null;
      }[]
    | null;
  totalAmount?: number | null;
  totalAmountclient?: number | null;
  remainingAmount?: number | null;
  description?: string | null;
  clientCreatedAt?: string | null;
  clientUpdatedAt?: string | null;
  paymentstatus?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-transaction".
 */
export interface VendorTransaction {
  id: number;
  vendorName: number | Vendor;
  query_license: number | Vendor;
  near_village: number | Vendor;
  workingStage?:
    | {
        workingStage?: string | null;
        workingDescription?: string | null;
        workstatus?: string | null;
        id?: string | null;
      }[]
    | null;
  workingStagevendor?:
    | {
        workingStagevendor?: string | null;
        workingDescriptionvendor?: string | null;
        id?: string | null;
      }[]
    | null;
  totalAmount?: number | null;
  totalAmountvendor?: number | null;
  remainingAmount?: number | null;
  description?: string | null;
  vendorCreatedAt?: string | null;
  vendorUpdatedAt?: string | null;
  paymentstatus?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor".
 */
export interface Vendor {
  id: number;
  vendorName: string;
  vendorMobile: string;
  query_license: string;
  mining_license?: string | null;
  near_village: string;
  tehsil?: string | null;
  district?: string | null;
  state?: string | null;
  country?: string | null;
  vendorCreatedAt?: string | null;
  vendorUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense".
 */
export interface Expense {
  id: number;
  nameOfExpense: string;
  initialBalanceAmount: number;
  addExpenseItems?:
    | {
        amount?: number | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  expenseCreatedAt: string;
  expenseUpdatedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'client-accounts';
        value: number | ClientAccount;
      } | null)
    | ({
        relationTo: 'client-transaction';
        value: number | ClientTransaction;
      } | null)
    | ({
        relationTo: 'vendor-transaction';
        value: number | VendorTransaction;
      } | null)
    | ({
        relationTo: 'expense';
        value: number | Expense;
      } | null)
    | ({
        relationTo: 'vendor';
        value: number | Vendor;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-accounts_select".
 */
export interface ClientAccountsSelect<T extends boolean = true> {
  clientName?: T;
  clientMobile?: T;
  query_license?: T;
  mining_license?: T;
  near_village?: T;
  tehsil?: T;
  district?: T;
  state?: T;
  country?: T;
  clientCreatedAt?: T;
  clientUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-transaction_select".
 */
export interface ClientTransactionSelect<T extends boolean = true> {
  clientName?: T;
  query_license?: T;
  near_village?: T;
  workingStage?:
    | T
    | {
        workingStage?: T;
        workingDescription?: T;
        workstatus?: T;
        id?: T;
      };
  workingStageclient?:
    | T
    | {
        workingStageclient?: T;
        workingDescriptionclient?: T;
        stageDate?: T;
        id?: T;
      };
  totalAmount?: T;
  totalAmountclient?: T;
  remainingAmount?: T;
  description?: T;
  clientCreatedAt?: T;
  clientUpdatedAt?: T;
  paymentstatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-transaction_select".
 */
export interface VendorTransactionSelect<T extends boolean = true> {
  vendorName?: T;
  query_license?: T;
  near_village?: T;
  workingStage?:
    | T
    | {
        workingStage?: T;
        workingDescription?: T;
        workstatus?: T;
        id?: T;
      };
  workingStagevendor?:
    | T
    | {
        workingStagevendor?: T;
        workingDescriptionvendor?: T;
        id?: T;
      };
  totalAmount?: T;
  totalAmountvendor?: T;
  remainingAmount?: T;
  description?: T;
  vendorCreatedAt?: T;
  vendorUpdatedAt?: T;
  paymentstatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense_select".
 */
export interface ExpenseSelect<T extends boolean = true> {
  nameOfExpense?: T;
  initialBalanceAmount?: T;
  addExpenseItems?:
    | T
    | {
        amount?: T;
        description?: T;
        id?: T;
      };
  expenseCreatedAt?: T;
  expenseUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor_select".
 */
export interface VendorSelect<T extends boolean = true> {
  vendorName?: T;
  vendorMobile?: T;
  query_license?: T;
  mining_license?: T;
  near_village?: T;
  tehsil?: T;
  district?: T;
  state?: T;
  country?: T;
  vendorCreatedAt?: T;
  vendorUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}